# Workflow name
name: Build and Deploy to Docker Hub

# Trigger the workflow on push events to the master branch
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    # Specify the runner environment
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Check Out Repo
      uses: actions/checkout@v2

    # Step 2: Log in to Docker Hub using credentials stored in GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }} # Docker Hub password

    # Step 3: Build the Docker image and push it to Docker Hub
    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: . # Path to the Docker build context
        file: ./docker/Dockerfile.user # Path to the Dockerfile
        push: true # Push the image to Docker Hub
        tags: ganeshvarma1/ci-cd:latest # Replace with your Docker Hub username and repository

    # Step 4: Verify the pushed Docker image by pulling it from Docker Hub
    - name: Verify Pushed Image
      run: docker pull ganeshvarma1/ci-cd:latest # Replace with your Docker Hub username and repository

    # Step 5: Deploy the Docker image to an EC2 instance
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
      # Hostname or IP address of the EC2 instance
      host: ${{ secrets.SSH_HOST }}
      # Username for SSH login
      username: ${{ secrets.SSH_USERNAME }}
      # Private SSH key stored in GitHub Secrets
      key: ${{ secrets.SSH_KEY }}
      # Commands to execute on the EC2 instance
      script: |
        # Pull the latest Docker image from Docker Hub
        sudo docker pull ganeshvarma1/ci-cd:latest
        # Stop the currently running container (if any)
        sudo docker stop web-app || true
        # Remove the stopped container (if any)
        sudo docker rm web-app || true
        # Run a new container with the latest image
        sudo docker run -d --name web-app -p 3005:3000 ganeshvarma1/ci-cd:latest
